name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment : Production
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        USERNAME: ${{secrets.USERNAME}}
        PASSWORD: ${{secrets.USERNAME}}
        POSTALCODE: ${{secrets.POSTALCODE}}
      run: USERNAME='${USERNAME}' PASSWORD='${PASSWORD}' POSTALCODE='${POSTALCODE}' npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
